.npmrc, src/_packages/@lunit/heatmap/.npmrc, src/_packages/@lunit/insight-viewer/.npmrc, src/_packages/@lunit/is-complex-polygon/.npmrc, src/_packages/@lunit/is-intersection/.npmrc, src/_packages/@lunit/is-polygon-area-greater-than-area/.npmrc, src/_packages/@lunit/mdx-code-block/.npmrc, src/_packages/@lunit/new-window/.npmrc, src/_packages/@lunit/opt-components/.npmrc, src/_packages/@lunit/opt-control-icons/.npmrc, src/_packages/@lunit/opt-login-components/.npmrc, src/_packages/@lunit/scalebar/.npmrc, src/_packages/@lunit/screenshot/.npmrc, src/_packages/@lunit/timeout/.npmrc, src/_packages/@lunit/use-dialog/.npmrc, src/_packages/@lunit/use-opt-control/.npmrc, src/_packages/@lunit/use-reset-time/.npmrc, src/_packages/@lunit/use-shortcut/.npmrc, src/_packages/@lunit/use-state-memo/.npmrc
Deleted .npmrc files in order to fix Travis error
=> Travis fix error

src/_packages/@lunit/opt-components/README.md, src/_packages/@lunit/opt-components/__stories__/DialogPaper.stories.tsx, src/_packages/@lunit/opt-components/components/DialogPaper.tsx
📄참고: https://material-ui.com/components/paper/
=> <DialogPaper> background color 수정, Storybook 추가

src/_packages/@lunit/insight-viewer/__pages__/Components/InsightViewer.mdx
=> insight-viewer 에서 startPanInteraction 관련 내용 추가 

README.md, package.json, src/_packages/@handbook/code-block/.npmrc, src/_packages/@handbook/components/.npmrc, src/_packages/@handbook/components/components/Example.tsx, src/_packages/@handbook/source/.npmrc, src/_packages/@handbook/source/README.md, src/_packages/@handbook/source/__pages__/Transpile.mdx, src/_packages/@handbook/source/__pages__/Transpile/filterExports.tsx, src/_packages/@handbook/source/__pages__/index.ts, src/_packages/@handbook/source/__tests__/api.test.ts, src/_packages/@handbook/source/__tests__/slicer.test.ts.bak, src/_packages/@handbook/source/index.ts, src/_packages/@handbook/source/transpile/api.js, src/_packages/@handbook/source/transpile/filterExports.ts.bak, src/_packages/@lunit/handbook/.npmrc, src/_packages/@lunit/heatmap/__pages__/HeatmapIndicator.mdx, src/_packages/@lunit/heatmap/__pages__/PosMapRendering.mdx, src/_packages/@lunit/heatmap/components/HeatmapScaleSVGImage.tsx, src/handbook/index.html, src/handbook/index.tsx
=> export block import 자동화

.yarn/sdks/prettier/index.js, .yarn/sdks/typescript/lib/tsserver.js
git clone 했을 때 vscode에서 인식을 못해서 
`yarn dlx @yarnpkg/pnpify --sdk vscode` 실행하고 커밋했습니다. 
https://yarnpkg.com/getting-started/editor-sdks#vscode
=> update yarn editors sdks

apps/insight-viewer-demo/package.json, yarn.lock
- Security issue 해결을 위한 라이브러리 업데이트
- `node_modules` 제거하고 재설치해야 할 수 있습니다 (`@emotion/react` 관련 문제인듯)
=> chore: Upgrade dependencies

apps/insight-viewer-demo/cypress/support/const.ts, apps/insight-viewer-demo/src/components/Button/index.tsx, apps/insight-viewer-demo/src/components/Layout/MobileNavigation.tsx, apps/insight-viewer-demo/src/components/Layout/index.tsx, apps/insight-viewer-demo/src/components/Nav/index.tsx, apps/insight-viewer-demo/src/components/Wrapper/index.tsx, apps/insight-viewer-demo/src/containers/Basic/ImageSelectableViewer.tsx, apps/insight-viewer-demo/src/containers/Basic/index.tsx, apps/insight-viewer-demo/src/containers/Error/Base.tsx, apps/insight-viewer-demo/src/containers/Error/Custom.tsx, apps/insight-viewer-demo/src/containers/Error/Tabs.tsx, apps/insight-viewer-demo/src/containers/HttpHeader/WithJwt.tsx, apps/insight-viewer-demo/src/containers/Interaction/Base.tsx, apps/insight-viewer-demo/src/containers/Interaction/Control/Click.tsx, apps/insight-viewer-demo/src/containers/Interaction/Control/index.tsx, apps/insight-viewer-demo/src/containers/Interaction/Custom.tsx, apps/insight-viewer-demo/src/containers/Interaction/Tabs.tsx, apps/insight-viewer-demo/src/containers/MultiFrame/Base.tsx, apps/insight-viewer-demo/src/containers/Overlay/index.tsx, apps/insight-viewer-demo/src/containers/Progress/Base.tsx, apps/insight-viewer-demo/src/containers/Progress/Custom.tsx, apps/insight-viewer-demo/src/containers/Progress/Tabs.tsx, apps/insight-viewer-demo/src/containers/Viewport/index.tsx, apps/insight-viewer-demo/src/hooks/useIsOneColumn.ts, apps/insight-viewer-demo/src/pages/_app.tsx, packages/insight-viewer/src/components/LoadingProgress/index.tsx, packages/insight-viewer/src/components/ViewerWrapper/index.tsx
Issue
---
https://app.asana.com/0/1200128631446379/1200618278948819/f
Feature
---
- 레이아웃 눈에 띄게 안맞는 부분 수정: 이걸로 인해 Percy 테스트 변경이 발생하므로 우선 진행합니다.
- 768px 기준으로 one-column, two-column 레이아웃 나누기 https://github.com/lunit-io/frontend-components/commit/5d2da64c1db661a864beafa89a25c1c6dc6c5ce4
Percy 테스트는 데스크탑 two-column 레이아웃으로 진행하므로 one-column 레이아웃은 대충 나누기만 했습니다.
추후 상세 진행합니다.
- Cypress 테스트에서 DOM 접근을 위한 data-attribute 추가 https://github.com/lunit-io/frontend-components/commit/f9216a97c336f640f95cd73a94bc56889cb637ae https://github.com/lunit-io/frontend-components/commit/2ef5ef669137ced0a64aa75e73b5879a9d6c8a59
데모는 기존대로 유지하고(너무 많다), Viewer에서만 data-attribute로 바꿨습니다.
=> Feature/update demo UI

packages/osd-react-renderer/.eslintrc.js, packages/osd-react-renderer/src/HostConfig/type.ts, packages/osd-react-renderer/src/ReactOSDDOM.tsx, packages/osd-react-renderer/src/elements/Base.tsx, packages/osd-react-renderer/src/elements/InvalidElement.tsx, packages/osd-react-renderer/src/elements/Root.tsx, packages/osd-react-renderer/src/elements/TiledImage.tsx, packages/osd-react-renderer/src/elements/Viewport.tsx, packages/osd-react-renderer/src/elements/index.tsx
merging back to osd-react-renderer dev branch
=> feat: Implements osd instance

apps/osd-viewer-demo/package.json, apps/osd-viewer-demo/src/App.tsx, yarn.lock
There's no css-in-js module installed on osd-viewer-demo
Added styled-components to osd-viewer-demo
=> chore(osd-viewer-demo): adding styled-components

.allstar/allstar.yaml, .allstar/binary_artifacts.yaml, .allstar/branch_protection.yaml, .allstar/outside.yaml, .allstar/security.yaml
Add [Allstar](https://github.com/ossf/allstar) Github App to set and enforce security policies
Example: https://github.com/lunit-io/insight-public/issues/172
=> chore(root): add allstar for enforcing security policies

.github/CODEOWNERS
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
reviewer 자동 설정이나 merge 조건 설정 등 여러모로 사용 가능한 기능입니다. 일단은 두 패키지에 대해서 한분씩 세팅했는데, 팀을 지정하는 것도 가능합니다.
=> setup code owners

apps/osd-viewer-demo/CHANGELOG.md, apps/osd-viewer-demo/package.json, packages/osd-react-renderer/CHANGELOG.md, packages/osd-react-renderer/package.json
- @lunit/osd-viewer-demo@1.0.0-alpha.6
- @lunit/osd-react-renderer@1.0.0-alpha.6
Released 1.0.0-alpha.6
=> chore(release): publish release

.github/workflows/insight-viewer-feature.yml, .github/workflows/insight-viewer-production.yml, .github/workflows/insight-viewer-staging.yml, packages/insight-viewer/src/components/ViewerWrapper/index.tsx
`node_modules` 자체를 저장하는 방법보다 yarn의 캐시 디렉토리를 저장하는 방법이 더 빠르다고 해서 테스트해보겠습니다. 
=> Improves Github actions cache for yarn install

apps/insight-viewer-docs/cypress/integration/viewport.spec.ts, apps/insight-viewer-docs/src/components/OverlayLayer/index.tsx, apps/insight-viewer-docs/src/containers/Viewport/Image1.tsx, apps/insight-viewer-docs/src/containers/Viewport/const.ts, packages/insight-viewer/src/const/index.ts, packages/insight-viewer/src/types/index.ts, packages/insight-viewer/src/utils/common/const.ts, packages/insight-viewer/src/utils/common/formatViewport.spec.ts, packages/insight-viewer/src/utils/common/formatViewport.ts
`Viewport`에 `rotation`을 추가합니다. 해당 속성이 이미 Cornerstone에 있기 때문에, 큰 수정은 없습니다. 
이에 따른 예제와 테스트도 추가되었습니다.
`rotation` 필드 누락으로 영상 회전 불가
`rotation` 추가로 영상 회전 가능
=> Add rotation property to viewport

.github/workflows/insight-viewer-feature.yml, .github/workflows/insight-viewer-production.yml, .github/workflows/insight-viewer-staging.yml
=> ci(root): cache node_modules on PR preview

README.md, insight-viewer.code-workspace
모노레포로 관리되다보니 검색, 폴더 별 이동에 있어서 조금 불편한 점들이 있어서 제의 드립니다.
장점
1. 검색 시 원하는 스코프 내에서의 검색 결과를 보기 편함. 
2. docs, package 간의 이동이 쉬워짐
3. 터미널을 여는 단축기 사용 시 어떤 위치에서 터미널을 사용할 건지 묻기 때문에 번거롭게 원하는 폴더 찾아서 그곳에서 터미널을 열지 않아도 됨
=> Chore/Add WorkSpace setup

packages/insight-viewer/src/Viewer/LineViewer/index.tsx, packages/insight-viewer/src/Viewer/PolylineDrawer/index.tsx, packages/insight-viewer/src/utils/common/getArrowPosition.ts, packages/insight-viewer/src/utils/common/getPolyProps.ts
arrow scale 변경 및 outline style 변경을 했습니다.
위 작업을 통해 outline style, arrow scale 버그를 수정했습니다.
arrow head 가 비정상적인 scale 로 표기됩니다. 
이와 더불어 outline style 이 존재하지 않습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-22, https://lunit.atlassian.net/browse/VIEWER-23
arrow outline style 을 추가했습니다. 471bbf1
INSIGHT View 기준 디자인의 scale 에 맞게 값을 조정했습니다. 0dd5758
=> VIEWER-22 / VIEWER-23 / add arrow outline style, modify arrow scale

packages/insight-viewer/src/Viewer/CircleDrawer/index.tsx, packages/insight-viewer/src/Viewer/CircleViewer/index.tsx
이전 PR에 빠졌던 숫자 3자릿 수 마다 쉼표를 넣는 기능을 추가하였습니다.
=> VIEWER-20 / change display circle measurement

.github/workflows/insight-viewer-production.yml, .github/workflows/insight-viewer-staging.yml, insight-viewer.code-workspace
`develop` 브랜치를 `insight-viewer.s.lunit.io`로, `master` 브랜치를 `insight-viewer.lunit.io`로 배포하는 Github action을 Nx 구성에 맞게 업데이트합니다.
Issue Number: [VIEWER-14]
`develop` 브랜치를 `insight-viewer.s.lunit.io`로, `master` 브랜치를 `insight-viewer.lunit.io`로 배포
[VIEWER-14]: https://lunit.atlassian.net/browse/VIEWER-14?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VIEWER-14 / Update Github actions for deploy

apps/insight-viewer-docs/containers/HttpHeader/WithJwt.tsx, libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx, libs/insight-viewer/src/Viewer/RulerViewer/index.tsx, libs/insight-viewer/src/const/index.ts, libs/insight-viewer/src/utils/common/calculateLengthBetweenPoints.spec.ts, libs/insight-viewer/src/utils/common/calculateLengthBetweenPoints.ts, libs/insight-viewer/src/utils/common/getLineLength.ts, libs/insight-viewer/src/utils/common/getRulerTextPosition.spec.ts, libs/insight-viewer/src/utils/common/getRulerTextPosition.ts
텍스트 출력 문제 위치 문제를 해결하였습니다
기존 텍스트 위치를 조금 상단으로 옮기고, 테스트 수정하였습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-47
=> Viewer-47 / modify text position

tools/scripts/publish.mjs
Publish command 에서 tag option 삭제를 반영했습니다.
이전 PR 에 반영해야하는데 놓쳐서 별도의 PR 로 다시 올렸습니다.
이미 논의된 내용이므로 바로 머지하겠습니다. https://github.com/lunit-io/frontend-components/pull/307#issuecomment-1247417529
publish 할 때 root package version 에 해당하는 태그가 생성됩니다.
release bump 과정에서 tagging 을 진행하므로 tag option 을 삭제했습니다. 26ff798
=> Hotfix / delete unused tag option of publish command

CHANGELOG.md, apps/insight-viewer-docs-e2e/CHANGELOG.md, apps/insight-viewer-docs/CHANGELOG.md, libs/fixtures/CHANGELOG.md, libs/fixtures/package.json, libs/insight-viewer/CHANGELOG.md, libs/insight-viewer/package.json, libs/insight-viewer/project.json, libs/insight-viewer/src/Viewer/Viewer.styles.ts, package.json, tools/scripts/publish.mjs
5.8.1 버전을 릴리즈합니다.
publish 내 불필요한 코드 제거 및 INSIGHT-Viewer 배포 중점으로 코드 수정 f48771d
publish command 내 tag option 제거 26ff798
version bump 및 CHANGELOG update 432780c
=> INSIGHT Viewer v5.8.1 release

CHANGELOG.md, apps/insight-viewer-docs-e2e/CHANGELOG.md, apps/insight-viewer-docs/CHANGELOG.md, libs/fixtures/CHANGELOG.md, libs/fixtures/package.json, libs/insight-viewer/CHANGELOG.md, libs/insight-viewer/package.json, libs/insight-viewer/src/Viewer/AnnotationViewer/index.tsx, libs/insight-viewer/src/Viewer/MeasurementViewer/index.tsx, libs/insight-viewer/src/Viewer/Viewer.styles.ts, package.json
5.8.2 버전을 릴리즈합니다.
Drawer 에도 pointer event 가 적용되어 있어 이를 삭제합니다. 2124d07
=> INSIGHT Viewer v5.8.2 release

CHANGELOG.md, apps/insight-viewer-docs-e2e/CHANGELOG.md, apps/insight-viewer-docs/CHANGELOG.md, apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx, libs/fixtures/CHANGELOG.md, libs/fixtures/package.json, libs/insight-viewer/CHANGELOG.md, libs/insight-viewer/package.json, libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.types.ts, libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx, libs/insight-viewer/src/Viewer/AnnotationOverlay/index.tsx, libs/insight-viewer/src/Viewer/PolylineDrawer/PolylineDrawer.types.ts, libs/insight-viewer/src/Viewer/PolylineDrawer/index.tsx, package.json
5.8.3 버전을 릴리즈합니다.
`showAnnotationLabel` prop 이 false, Edit 기능 활용 시 label 이 표기되는 버그 수정 d90bb32
docs 에 `showAnnotationLabel` 설정을 위한 스위치 추가 fd4414c
=> INSIGHT Viewer v5.8.3 release

libs/insight-viewer/src/hooks/useImage/index.ts
[VIewer-52 PR](https://github.com/lunit-io/frontend-components/pull/315) 에서 잘못된 부분을 수정하였습니다
=> Viewer-52 / Fix parameterize useImage's HTTP client

CHANGELOG.md, apps/insight-viewer-docs-e2e/CHANGELOG.md, apps/insight-viewer-docs/CHANGELOG.md, libs/fixtures/CHANGELOG.md, libs/fixtures/package.json, libs/insight-viewer/CHANGELOG.md, libs/insight-viewer/package.json, libs/insight-viewer/src/hooks/useImage/index.ts, package.json
5.9.1 버전을 릴리즈합니다.
HTTP Client type 문제로 인한 수정 https://github.com/lunit-io/frontend-components/pull/320
=> INSIGHT Viewer v5.9.1 release

libs/insight-viewer/src/hooks/useImage/index.ts, libs/insight-viewer/src/hooks/useImageLoader/index.ts
즉시 실행 함수가 있던 부분을 수정하였습니다.
진행 중에 상엽님과 useImage 에 `onImageLoaded` 에 대해서 잠깐 이야기를 나누었는데, 현재는 이미지가 렌더링이 끝난 후에 onImageLoaded 에 넣어둔 함수를 실행시키기 위해 억지로 setTimeout을 이용하여 구현이 되어있는 상태이고 추후에는 useImage를 쪼개고 이 부분은 훅이아닌 컴포넌트 쪽으로 빠지는게 좋을 것 같다는 이야기가 나왔습니다.
=> VIEWER-49 / Remove IIFE

CHANGELOG.md, apps/insight-viewer-docs-e2e/CHANGELOG.md, apps/insight-viewer-docs/CHANGELOG.md, libs/fixtures/CHANGELOG.md, libs/fixtures/package.json, libs/insight-viewer/CHANGELOG.md, libs/insight-viewer/package.json, libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx, package.json
5.9.2 버전을 릴리즈합니다.
measurement ruler 의 text move 기능이 정상 동작하지 않는 버그를 수정합니다. https://github.com/lunit-io/frontend-components/pull/322
=> INSIGHT Viewer v5.9.2 release

libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.types.ts, libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx, libs/insight-viewer/src/Viewer/AnnotationOverlay/index.tsx, libs/insight-viewer/src/Viewer/MeasurementDrawer/MeasurementDrawer.types.ts, libs/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx, libs/insight-viewer/src/Viewer/MeasurementOverlay/index.tsx, libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts, libs/insight-viewer/src/hooks/useAnnotationPointsHandler/types.ts, libs/insight-viewer/src/hooks/useDrawingHandler/index.ts, libs/insight-viewer/src/hooks/useDrawingHandler/types.ts, libs/insight-viewer/src/hooks/useMeasurement/index.ts, libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts, libs/insight-viewer/src/hooks/useMeasurementPointsHandler/types.ts
https://lunit.atlassian.net/browse/VIEWER-67
Measurement, Annotation 모드에서 그려진 도형 위에 마우스가 호버 상태가 되었을 때 drawing이 작동하지 않도록 변경하였습니다
도형 위에 호버가 된상 태에서 드래깅 시 도형을 추가로 그릴 수 있음
도형 위에 호버가 된상 태에서 드래깅 시 도형을 추가로 그릴 수 없습니다.
=> VIEWER-67 / Prevent dragging when hovered 

libs/insight-viewer/src/Viewer/HeatmapViewer/index.tsx, libs/insight-viewer/src/Viewer/LineViewer/index.tsx, libs/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx, libs/insight-viewer/src/Viewer/MeasurementOverlay/index.tsx, libs/insight-viewer/src/Viewer/MeasurementViewer/index.tsx, libs/insight-viewer/src/Viewer/PolygonViewer/index.tsx, libs/insight-viewer/src/Viewer/PolylineDrawer/index.tsx, libs/insight-viewer/src/Viewer/TextDrawer/index.tsx, libs/insight-viewer/src/Viewer/index.tsx, libs/insight-viewer/src/contexts/index.tsx, libs/insight-viewer/src/utils/common/getDrewAnnotation.ts, libs/insight-viewer/src/utils/common/getInitialAnnotation.ts
=> Refactor / general refactoring

libs/insight-viewer/src/components/EditPointer/index.tsx
Release/5.10.0의 변경 사항 중, 반영이 안된 부분이 있어서 추가로 PR 올립니다.
=> Fix Release/5.10.0

libs/insight-viewer/src/Viewer/AnnotationViewer/index.tsx, libs/insight-viewer/src/Viewer/MeasurementOverlay/MeasurementOverlay.types.ts, libs/insight-viewer/src/Viewer/MeasurementOverlay/index.tsx, libs/insight-viewer/src/Viewer/MeasurementViewer/MeasurementViewer.types.ts, libs/insight-viewer/src/Viewer/MeasurementViewer/index.tsx, libs/insight-viewer/src/hooks/useAnnotation/index.ts, libs/insight-viewer/src/hooks/useMeasurement/index.ts
현재 develop 버전 내에서 Edit 기능이 정상동작하지 않습니다.
아래 두 작업에 대한 사이드 이펙트로 확인됩니다. 
[annotation, measurement hover 시 drawing 하지 않도록 기능 구현](https://github.com/lunit-io/frontend-components/pull/329) 
[select 시 annotation list 제외하지 않는 쪽으로 리팩토링](https://github.com/lunit-io/frontend-components/pull/328)
Annotation, Measurement Edit 기능이 동작하지 않습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-75
Annotation, Measurement Edit 기능이 동작합니다.
---
1. hover 상태일 경우, Drawing 하지 않는 기능을 구현하기 위해 mouse event 에 조건문을 걸었습니다.
(hover 상태일 때 이벤트 등록을 하지 않도록)
2. select 할 경우, annotation list 에서 삭제하지 않도록 리팩토링을 진행
이 과정에서 select 시 remove 기능을 삭제 (remove 기능 내에서 hovered annotation 을 null 로 초기화)
hovered annotation 이 초기화하지 않아, edit 시 hovered annotation 이 있다고 판단되어
event 가 등록을 하지 않습니다.
3. 2 …
=> VIEWER-75 / Fix Edit not working bug

libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx
Circle Drawer 에서 삭제 과정에서 누락된 cursor style 을 삭제했습니다.
Circle Drawer 의 extends area 에 cursor style 이 적용되어 있습니다.
Circle Drawer 의 extends area 에 cursor style 을 삭제했습니다.
=> hotfix / delete circle drawer cursor style

.github/workflows/insight-viewer-production.yml
=> chore(docs): remove space in yml

apps/insight-viewer-docs/containers/Interaction/Image2.tsx, libs/insight-viewer/src/hooks/useInteraction/types.ts, libs/insight-viewer/src/hooks/useInteraction/useHandleWheel/control.ts, libs/insight-viewer/src/hooks/useInteraction/useHandleWheel/index.ts, libs/insight-viewer/src/hooks/useInteraction/useViewportInteraction.ts
마우스 휠 interaction 에 대한 기본 동작을 정의합니다.
기본 동작에 대한 스펙 논의가 필요할 것 같습니다.
mouse wheel 기본 동작이 정의되어 있지 않습니다.
이를 사용해야할 경우 외부에서 별도의 함수를 구현해서 Interaction 에 전달해야합니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-88
mouse wheel scale 기본 동작을 정의했습니다.
이제 별도의 함수 구현 없이 interaction mouse wheel 에 'scale' 문자열을 기입할 경우
정의된 기본 함수가 동작합니다.
mouse wheel scale handling 을 위한 type 을 정의했습니다. 024bb98
mouse wheel scale 기본 동작 방식을 정의했습니다. 632a812
mouse wheel scale 기본 동작 방식을 useHandleWheel hook 에 적용했습니다. d146145
기본 동작은 mouseWheel field 값을 'scale' 로 전달했을 경우 동작하며,
외부에서 정의된 함수가 있을 경우, 해당 함수를 실행하도록 구현했습니다.
mouse wheel handling function params 중 wheelType 을 삭제 조치했습니다. 4ac6cc5
drag 와 달리 secondary, primary 동작이 구분되어 있지 않으므로 굳이 필요없는 필드라고 판단되어
삭제 조치했습니다.
=> VIEWER-88 / add default mouse wheel interaction function

apps/insight-viewer-docs-e2e/src/e2e/annotation.drawer.cy.ts
지난 PR에 추가된 arrow line 관련 테스트를 추가하였습니다. 
arrow line 추가와 arrow line 삭제에 대한 테스트 입니다. 
=> VIEWER-96 / add arrow line annotation test

.github/workflows/dev-e2e-test.yml, .github/workflows/insight-viewer-unit-test.yml, apps/insight-viewer-dev-e2e/cypress.config.ts, apps/insight-viewer-dev-e2e/src/e2e/annotation.drawer.cy.ts, apps/insight-viewer-dev-e2e/src/e2e/measurement.drawer.cy.ts, apps/insight-viewer-dev-e2e/src/support/utils.ts
INSIGHT Viewer 라이브러리, dev 의 Unit, E2E 테스트 Github actions 를 추가합니다.
이를 통해 각 PR 올릴 단계에서 테스트 통과 여부를 확인하고자 합니다.
테스트 관련 github action 이 없습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-110
Cypress E2E, unit test 에 대한 github actions 가 있습니다.
이를 통해 PR 올릴 단계에서 테스트 통과 여부를 확인할 수 있습니다.
=> VIEWER-110 / Add unit, e2e test github actions

.github/workflows/insight-viewer-unit-test.yml, README.md
README 내 이전 버전에 해당하는 내용 수정 및 해당 라이브러리의 목적 및 사용법을 상세하게 기입했습니다.
추가된 내용에서 수정이 필요한 사항 혹은 좀 더 추가할 내용이 있다면 코멘트 부탁드립니다.
구 버전 git clone 주소가 기입되어있습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-154
현재 버전 git clone 주소가 기업되어 있으며,
설치 방법, 라이브러리에 대한 설명이 보다 상세하게 작성되어 있습니다.
=> VIEWER-154 / update README

README.md, libs/annotation/README.md, libs/fixtures/README.md, libs/insight-viewer/README.md, libs/viewport/README.md
insight-viewer README 에 Annotation, Dicom Viewer, Interaction 에 대한 기본적인 예시를 추가했습니다.
_(많은 사용이 예상되는 기능을 선정하여 작성했습니다.)_
기본 예시는 React 기본 세팅에서 라이브러리 설치 후 App 에서 바로 실행할 수 있도록 작성했습니다.
더불어 annotation, viewport, insight-viewer 라이브러리의 README 도
목적에 대한 코멘트를 추가하여 업데이트 했습니다.
- [Root README](https://github.com/lunit-io/insight-viewer/blob/docs/VIEWER-161-update-readme/README.md)
각 라이브러리 README 는 nx 기본 README 로 구성되어 있습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-161
insight-viewer 라이브러리 root README 에 기본 예제를 추가했으며,
세부 라이브러리의 README 에도 목적에 대한 코멘트를 추가했습니다.
=> VIEWER-161 / 라이브러리 README 업데이트

CHANGELOG.md, apps/insight-viewer-dev-e2e/CHANGELOG.md, apps/insight-viewer-dev/CHANGELOG.md, libs/annotation/CHANGELOG.md, libs/annotation/package.json, libs/fixtures/CHANGELOG.md, libs/fixtures/package.json, libs/insight-viewer/CHANGELOG.md, libs/insight-viewer/README.md, libs/insight-viewer/package.json, libs/viewport/CHANGELOG.md, libs/viewport/package.json, package.json
NPM 에 표기될 Repo, homepage, keyword, README 표기 업데이트가 반영된 7.0.1 Patch version 릴리즈를 진행합니다.
=> 7.0.1 version Patch Release

CHANGELOG.md, apps/insight-viewer-dev-e2e/CHANGELOG.md, apps/insight-viewer-dev/CHANGELOG.md, apps/insight-viewer-dev/containers/Annotation/Drawer/index.tsx, apps/insight-viewer-dev/styles/globals.css, libs/annotation/CHANGELOG.md, libs/annotation/package.json, libs/annotation/src/components/AnnotationDrawer/index.tsx, libs/annotation/src/components/AnnotationOverlay/utils/addAnnotation.ts, libs/annotation/src/components/AnnotationViewer/index.tsx, libs/annotation/src/components/PointDrawer/PointDrawer.types.ts, libs/annotation/src/components/PointDrawer/index.tsx, libs/annotation/src/components/PointViewer/PointViewer.types.ts, libs/annotation/src/components/PointViewer/index.tsx, libs/annotation/src/const.ts, libs/annotation/src/hooks/useCreatingDrawableAnnotation/index.ts, libs/annotation/src/types.ts, libs/annotation/src/utils/createInitialAnnotation.ts, libs/annotation/src/utils/getAnnotationPoints.ts, libs/annotation/src/utils/getEditPointPosition.ts, libs/annotation/src/utils/getPointsUpdatedAnnotation.ts, libs/annotation/src/viewer.styles.ts, libs/fixtures/CHANGELOG.md, libs/fixtures/package.json, libs/insight-viewer/CHANGELOG.md, libs/insight-viewer/package.json, libs/viewport/CHANGELOG.md, libs/viewport/package.json, package.json
Point Annotation 추가 및 기존 data Attribute 가 적용되지 않는 이슈를 해결합니다.
위 작업 사항을 반영한 7.1.0 version 릴리즈를 진행합니다.
=> 7.1.0 version Minor Release

CHANGELOG.md, apps/insight-viewer-dev-e2e/CHANGELOG.md, apps/insight-viewer-dev/CHANGELOG.md, libs/annotation/CHANGELOG.md, libs/annotation/package.json, libs/fixtures/CHANGELOG.md, libs/fixtures/package.json, libs/insight-viewer/CHANGELOG.md, libs/insight-viewer/package.json, libs/viewport/CHANGELOG.md, libs/viewport/package.json, package.json
아래 변경 사항을 포함한 7.2.0 릴리즈 용 PR 입니다.
CHANGELOG 및 version bump 를 진행합니다.
- CXR4 용 Heatmap Viewer 추가
- React v18 peer dependency 업데이트
=> 7.2.0 version Minor Release

CHANGELOG.md, apps/insight-viewer-dev-e2e/CHANGELOG.md, apps/insight-viewer-dev/CHANGELOG.md, libs/annotation/CHANGELOG.md, libs/annotation/package.json, libs/fixtures/CHANGELOG.md, libs/fixtures/package.json, libs/insight-viewer/CHANGELOG.md, libs/insight-viewer/package.json, libs/viewport/CHANGELOG.md, libs/viewport/package.json, package.json
7.2.0 배포 버전에서 일부 패키지가 미포함된 이슈가 있어
새로운 버전을 릴리즈 합니다.
=> 7.2.1 version Patch Release

CHANGELOG.md, apps/insight-viewer-dev-e2e/CHANGELOG.md, apps/insight-viewer-dev/CHANGELOG.md, libs/annotation/CHANGELOG.md, libs/annotation/package.json, libs/fixtures/CHANGELOG.md, libs/fixtures/package.json, libs/insight-viewer/CHANGELOG.md, libs/insight-viewer/package.json, libs/viewport/CHANGELOG.md, libs/viewport/package.json, package.json
7.2.0 ~ 7.2.1 배포 버전에서 일부 패키지가 미포함된 이슈를 해결한 버전입니다.
=> 7.2.2 version Patch Release
