src/_packages/@lunit/opt-components/__pages__/Basic.mdx, src/_packages/@lunit/opt-components/__pages__/Sample.tsx, src/_packages/@lunit/opt-components/__pages__/index.ts, src/_packages/@lunit/opt-components/components/QuarterView.tsx, src/_packages/@lunit/opt-components/package.json, src/handbook/index.tsx
QuarterView 컴포넌트에 useShortcut 을 적용하고 단축키를 props 로 전달받아 이용할 수 있게 수정.
(Shortcut 관련 부분 코드를 아름답게 혹은 깔끔하게 정리할 수 있는 방법은 없을까요)
Handbook 에서 확인할 수 있게 파일도 생성해 두었으니 확인하고 싶을 때 handbook/index에 페이지를 등록해 확인할 수 있음.
=> opt-component/QuarterView 에 useShortcut 적용

packages/insight-viewer/src/hooks/useMultiframe/usePrefetch.ts
다른 피처 작업해보다 발견한건데 `try catch`가 콜백 안의 에러를 잡지 못해서 `Uncaught (in promise)` 에러가 그대로 나고 있었네요.
일단 에러나면 onError() 제대로 호출한 다음 나머지 이미지만 불러오게끔 수정했습니다.
재현은 Multiframe 데모에서 존재하지 않는 이미지를 `IMAGES`에 넣어보시면 됩니다.
=> fix: handle errors on prefetch

apps/osd-viewer-demo/src/App.tsx, packages/osd-react-renderer/src/elements/Base.tsx, packages/osd-react-renderer/src/elements/Scalebar.ts, packages/osd-react-renderer/src/elements/index.tsx, packages/osd-react-renderer/src/index.ts, packages/osd-react-renderer/src/plugins/OpenSeadragonScalebar.js, packages/osd-react-renderer/src/types/index.ts
There's no way to add scale bar to OpenSeadragon using our react renderer
Issue Number: https://app.asana.com/0/1200587746109495/1200843168588504/f
Now we can add scale bar to OpenSeadragon using our react renderer as following:
```
<OSDViewer>
<scalebar
pixelsPerMeter={1e6 / 0.263175}
xOffset={10}
yOffset={30}
location={ScalebarLocation.BOTTOM_RIGHT}
...
/>
</OSDViewer>
```
=> feat(osd-react-renderer): added scalebar as a host component

.eslintrc.js, apps/insight-viewer-docs/src/containers/DicomfileViewer/Code.ts, apps/insight-viewer-docs/src/containers/DicomfileViewer/index.tsx, packages/insight-viewer/src/hooks/useDicomFile/index.ts, packages/insight-viewer/src/types/index.ts
- @lunit/insight-view의 useDicomFile()로부터 file expose 하기
dicom 파일을 업로드하여 뷰어에서 사용하는 경우, 업로드한 File 또는 file.name이 필요한 경우가 있다.
- @lunit/insight-view의 useImage/useMultipleImages에서 이미지 아이디를 받을 때, 이미지 아이디가 undefined인 경우를 허용하도록 한다. 현재는 string만 허용.
dicom 파일을 업로드하여 뷰어에서 사용하는 경우 useDicomFile() hook을 사용하는 데, 이 때 이미지 아이디가 undefined인 경우가 있을 수 있다.
```tsx
const { imageId, setImageIdByFile } = useDicomFile()
```
```ts
export type ImageId =
| {
[IMAGE_LOADER_SCHEME.WADO]: string | string[]
[IMAGE_LOADER_SCHEME.DICOMFILE]?: never
[IMAGE_LOADER_SCHEME.WEB]?: never
}
| {
[IMAGE_LOADER_SCHEME.WADO]?: never
[IMAGE_LOADER_SCHEME.DICOMFILE]: string | string[]
[IMAGE_LOADER_SCHEME.WEB]?: never
}
| {
[IMAGE_LOADER_SCHEME.WADO]?: never
[IMAGE_LOADER_SCHEME.DICOMFILE]?: …
```
=> Feature/expose file from use dicom file hook #139

packages/osd-react-renderer/src/plugins/OpenSeadragonCanvasOverlay.js, packages/osd-react-renderer/src/plugins/OpenSeadragonTooltipOverlay.js
- Add a `'close'` handler in `canvasOverlay` and `tooltipOverlay` to prevent from redrawing when the viewer is closed.
When the url of `tiledImage` changes, `Overlay.forceRedraw` method caused a runtime error as above. This issue is because it internally accesses to the current image, which is already destroyed. To be more specific, (1) changing the url triggers the viewer to be closed and opened again, (2) the image object is cleared by `Viewer.close()`, and (3) the overlay crashes because `var image1 = this._viewer.world.getItemAt(0)` would return undefined.
`Overlay.forceRedraw` method does not crash when the url of `tiledImage` changes.
=> fix(osd-react-renderer): fix a bug where changing the url of a tiledImage caused a crash

packages/osd-react-renderer/src/elements/TiledImage.ts, packages/osd-react-renderer/src/types/index.ts
- Use `tileSource` for tiling instead of `dziMeta` and `tileMap`.
It is currently difficult to initialize TiledImage with custom tileSource(s). For example, AIoP oncology uses the following custom tileSource to load tile images from the server:
```ts
async function loadCustomTile(slidePath: string) {
const { tiles_bin_url, tile_indices_url, dzi_meta_url } = await fetch(
`${API_URL}${IMG_PREFIX}/public/slides/url${slidePath}`
).then((res) => res.json());
const tileIndices = await fetch(tile_indices_url).then((res) => res.json());
const { format, ...tileSource } = await loadDZIMeta(dzi_meta_url);
return {
...tileSource,
getTileUrl: () => tiles_bin_url,
tileExists: (level, x, y) => tileIndices[`${level} ${x}_${y}`] !== undefined, …
```
=> fix(osd-react-renderer): added support for custom tileSource

packages/osd-react-renderer/src/elements/Viewport.ts
This PR fixes an issue where the min / max zoom level is not applied.
The minimum and maximum zoom level of a viewport is fixed to 0.1 / 160, even if the customized level is given from the user.
Given min / max zoom level is applied properly.
1. eslint 규칙으로 에러가 발생해서 이 부분을 수정했는데, 이게 제 로컬 환경에서 lint 설정이 잘못되어 있어서 발생한건지 잘 모르겠네요. 
2. 바쁘신 와중에 코드 리뷰를 위해 시간 내어주셔서 감사합니다, 수정 필요한 부분이 있으면 코멘트 부탁드립니다! 🙇‍♂️
=> fix(osd-react-renderer): fix min / max zoom level is not applied

.github/workflows/insight-viewer-production.yml
insight-viewer production github action을 기존 PR할 때 실행하는 대신 master 브랜치에 merge 할 때 실행하도록 바꾼다.
feature 브랜치를 push 할 때 feature action이 실행되는데, master에 PR을 하면서
feature 액션과 production 액션이 동시에 실행되기 때문.
=> chore(root): trigger production github action on push to master

packages/osd-react-renderer/src/plugins/OpenSeadragonCanvasOverlay.js, packages/osd-react-renderer/src/plugins/OpenSeadragonTooltipOverlay.js
> 1. fix an error when trying to change the source of tiledImage after any tiledImage is loaded on a viewport once.
=> fix(osd-react-renderer): fix crash error when switching tiledImage

packages/osd-react-renderer/src/types/index.ts
Implement canvas-contextmenu event from openseadragon
We re now able to use contextMenu
`<viewport
onCanvasContextMenu={handleCanvasContextMenu}
/>`
=> implement canvas-contextmenu event

apps/insight-viewer-docs/src/containers/UseOverlayContext/Heatmap/Heatmap.tsx
- insight-viewer 의 OverlayContext cornerstone util function 추가, interface 변경에 따라
insight-viewer-docs 의 Heatmap draw function props interface 도 변경해야하는 공수 발생 이슈가 있어
이에 대한 조치 PR 입니다.
- 기존 Omit 으로 제외하는 방법에서 Pick 을 사용하는 방식으로 수정하였습니다.
Omit 의 경우 OverlayContext interface 에 추가될 때마다 Omit List 에 추가해야하므로,
Pick 을 통해 위 문제를 해결했습니다.
- code review
- in svg Contour Viewer: https://github.com/lunit-io/frontend-components/pull/168#discussion_r774369492
- in svg Contour Drawer: https://github.com/lunit-io/frontend-components/pull/175#discussion_r779193125
- OverlayContext 의 cornerstone util function 이 추가될 때마다 interface 역시 해당 util function 에 대한
정의가 추가되며, 이에 따른 Omit 의 list 가 계속 늘어가게 됩니다.
Issue Number: https://github.com/lunit-io/frontend-components/issues/176
- Omit …
=> refactor(viewer-docs): modify draw props type Using Omit to Pick

.github/workflows/insight-viewer-feature.yml, .github/workflows/insight-viewer-production.yml, .github/workflows/insight-viewer-staging.yml, apps/insight-viewer-docs/src/containers/Contour/index.tsx, apps/insight-viewer-docs/src/pages/contour.tsx, package.json, packages/insight-viewer/package.json, packages/insight-viewer/scripts/compile, packages/insight-viewer/scripts/prepublish, packages/insight-viewer/scripts/publish, packages/insight-viewer/src/cjs/contour.ts, packages/insight-viewer/src/cjs/index.ts, scripts/build, scripts/local-publish, scripts/local-unpublish, scripts/prepublish, yarn.lock
ISSUE: https://github.com/lunit-io/frontend-components/issues/185
https://github.com/lunit-io/frontend-components/pull/173 caused two problems.
The PR is to expose the sub package from the subpath, e.g. @lunit/insight-viewer/contour.
To do this, I changed the package publishing path from the package root to the dist directory.
Here the mistake is to confuse npm publish with lerna publish.
I ran the command from the package root.
```bash
cd dist && yarn lerna publish
```
But I should have published from the workspace root with lerna command, because the project is managed with Lerna and Yarn workspace.
Lerna allow to customize the published subdirectory with publishConfig.directory, so I set the publish directory to /dist. https://github.com/lunit-io/frontend-components/pull/190/commits/64f …
=> Feature/fix package publish bug #185

apps/insight-viewer-docs/src/components/OverlayLayer/index.tsx, apps/insight-viewer-docs/src/containers/Interaction/Canvas.tsx, apps/insight-viewer-docs/src/containers/Interaction/Control/index.tsx, apps/insight-viewer-docs/src/containers/Interaction/Custom.tsx, apps/insight-viewer-docs/src/containers/Interaction/Image1.tsx, packages/insight-viewer/src/hooks/useInteraction/const.ts, packages/insight-viewer/src/hooks/useInteraction/types.ts, packages/insight-viewer/src/hooks/useInteraction/useHandleDrag/control.ts, packages/insight-viewer/src/hooks/useInteraction/useHandleDrag/index.ts, packages/insight-viewer/src/index.ts
마우스 드래그 동작으로 기존에 지원하던 이동, 윈도우 조절 외에 줌 인 / 아웃을 추가합니다.
드래그를 통한 줌 방식은 애플리케이션마다 다르나, 여기서는 INSIGHT View에서 사용할 `우측으로 드래그하면 줌 인, 좌측으로 드래그하면 줌 아웃`을 구현했습니다.
줌 기준점은 영상 중앙이 아닌 마우스 드래그 시작점이며, 이 기능은 휠을 통한 줌에도 차후 적용할 예정입니다.
`{ setInteraction } = useInteraction()`의 `primaryDrag`, `secondaryDrag`에 `'pan'`, `'adjust'` 만 사용 가능
`'zoom'` 추가 
기존에 뷰어에서 익스포트하던 `DragEvent` 타입의 명명이 혼동을 가져올 수 있어 `DragAction`으로 변경하였습니다. 기존 타입은 deprecated 표시하였으며 여전히 사용 가능합니다.
=> Add zoom by drag feature to interaction hook

packages/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx, packages/insight-viewer/src/Viewer/PolylineDrawer/PolylineDrawer.types.ts, packages/insight-viewer/src/Viewer/PolylineDrawer/index.tsx
Polygon Annotation을 edit 모드에서 선택 시 끝점 연결이 사라지는 문제를 해결했습니다.
=> fix(viewer): show polygon closing line while editing

apps/insight-viewer-docs/src/containers/Annotation/Drawer/index.tsx
Annotation docs 에서 arrow head mode 를 선택할 수 있는 radio 를 추가했습니다.
기본 normal 상태이며 arrow 를 선택할 시, arrow line 을 그릴 수 있습니다.
arrow head mode 를 선택할 수 없어 normal line 만 그릴 수 있습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-21
arrow head mode 를 선택할 수 있어, normal, arrow line 을 그릴 수 있습니다. ebbb851
=> VIEWER-21 / add arrow head mode radio to Annotation docs

apps/insight-viewer-docs/src/containers/Basic/Code.ts, packages/insight-viewer/src/const/index.ts, packages/insight-viewer/src/hooks/useImage/index.ts, packages/insight-viewer/src/hooks/useImage/loadCornerstoneImage.ts, packages/insight-viewer/src/hooks/useImage/loadImage.ts, packages/insight-viewer/src/hooks/useImage/types.ts, packages/insight-viewer/src/hooks/useMultipleImages/index.ts, packages/insight-viewer/src/hooks/useMultipleImages/loadCornerstoneImages.ts, packages/insight-viewer/src/hooks/useMultipleImages/loadImages.ts, packages/insight-viewer/src/hooks/useMultipleImages/useLoadImages.ts, packages/insight-viewer/src/utils/httpClient/index.ts
`useImage()` 및 `useMultipleImages()` 사용 시 기본 타임아웃인 10초를 60초로 늘리고, `timeout` 옵션으로 변경 가능하게 합니다.
이미지 로딩이 10초 이상 걸리면 실패합니다.
Issue Number: [VIEWER-27]
이미지 로딩이 60초 이상 걸리면 실패하며, timeout 옵션으로 변경 가능합니다.
[VIEWER-27]: https://lunit.atlassian.net/browse/VIEWER-27?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VIEWER-27 / Add timeout option to useImage

apps/insight-viewer-docs/mocks/lines.ts, packages/insight-viewer/src/types/index.ts, packages/insight-viewer/src/utils/common/getDrewAnnotation.ts, packages/insight-viewer/src/utils/common/getPolyProps.ts
Line Annotation 의 headPoints field 값을 삭제한 후, hasArrowHead field 를 추가했습니다.
위 방식을 통해 사용자 입장에서는 mock data 구성 시 arrow head 에 대한 별도의 계산을 할 필요가 없습니다.
기존에는 headPoints field 내에 arrow head points 좌표계를 들고 있었습니다.
이를 기반으로 pixelToCanvas 를 적용하여 arrow head 를 drawing 했습니다.
위 방식으로 인해 Dicom Image 에 따라 arrow head 의 비율이 다르게 표기됩니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-22, https://lunit.atlassian.net/browse/VIEWER-29
사용하지 않는 headPoints field 를 삭제한 후 arrow mode 일 때 drawing 했는지 여부를 알 수 있는
hasArrowHead field 를 추가하여 arrow head 계산 여부를 결정합니다.
기존 line head 의 mock data 가 있을 경우 수정이 필요합니다. 
headPoints field 삭제해야합니다.
=> VIEWER-29 / Delete headPoints field, add hasArrowHead field to Line Annotation

packages/insight-viewer/src/const/index.ts, packages/insight-viewer/src/utils/common/getDrewAnnotation.ts
Line Annotation Label position 이 start point 와 근접하게 위치하고 있습니다.
이로 인해 arrow mode 일 때 arrow head 가 잘 보이지 않는 문제가 발생하기에,
적절한 간격을 추가하여 이를 해결하고자 합니다.
Ruler 에 사용한 간격을 사용하려 했는데, Ruler 는 Line 과 달리 polylabel 라이브러리를 사용하지 
않아 간격의 차이가 존재하네요. 이는 Ruler text position 에 polylabel 을 적용하여
같은 값을 공유할 수 있도록 개선할 예정입니다.
기존 Line Annotation 의 label position 은 start point 에 근접해있습니다.
이로 인해 arrow head 가 가려지는 문제가 발생합니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-28
Line Annotation 에 적절한 간격을 적용하여 위 문제를 해결했습니다.
=> feat(viewer): add line spacing and apply line annotation label position

apps/insight-viewer-docs/src/containers/Basic/Code.ts, apps/insight-viewer-docs/src/containers/Basic/ImageSelectableViewer.tsx
View에서 코덱 세팅을 위해 로더 설정을 참고하다가 발견한 버그입니다. 예시를 위해 localhost:3000을 기입했는데 실제 동작에서도 사용되고 있었네요.
[VIEWER-6] 의 원인일 가능성도 있어보입니다.
docs 배포에서 콘솔에 에러 표시되고 이미지 로딩되지 않음
이미지가 정상적으로 로드됨
[VIEWER-6]: https://lunit.atlassian.net/browse/VIEWER-6?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(viewer-docs): wrong hostname in loader worker setting

packages/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts, packages/insight-viewer/src/utils/common/getDrewAnnotation.ts
Annotation Edit 기능을 통해 수정할 경우, 기존 label 에서 `마지막 label number + 1` 로 변경되는 버그를 수정했습니다.
Edit 기능을 사용하더라도 동일한 label 을 표기해야한다고 생각하기에 위와 같이 수정했습니다.
Annotation 에 Edit 기능 사용 시, 기존 label 을 표기하는 것이 아닌 `마지막 label number + 1` 을 표기하고 있습니다.
https://user-images.githubusercontent.com/88369343/182541536-d41605b0-3db7-44e9-a844-56faf12618e5.mov
Issue Number: https://lunit.atlassian.net/browse/VIEWER-33
Edit 기능 사용 시 기존 label 로 표기합니다.
=> VIEWER-33 / apply selectedAnnotation Id to addDrewAnnotation logic

packages/insight-viewer/src/hooks/useImage/loadImage.spec.ts, packages/insight-viewer/src/hooks/useMultipleImages/loadImages.spec.ts
https://github.com/lunit-io/frontend-components/pull/273 의 timeout 설정 추가로 인하여
loadImage, loadImages test code 가 실패하고 있습니다. timeout 을 추가하여 해결했습니다.
테스트 코드 관련 티켓이 머지될 시점에 테스트 코드에 대한 github action 이 필요할 것 같네요 🤔
loadImage, loadImages 에 대한 테스트 코드가 실패하고 있습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-32
loadImage, loadImages 에 대한 테스크 코드가 성공합니다.
loadImages test code 에 timeout 반영 [a626fde](https://github.com/lunit-io/frontend-components/pull/278/commits/a626fde74eebcaabb23b303140186a679e392826)
loadImage test code timeout 반영 [e338023](https://github.com/lunit-io/frontend-components/pull/278/commits/e338023561079e3314f8e0e5416d756268803dc7)
=> VIEWER-32 apply timeout arguments to loadImages test code

packages/insight-viewer/src/Viewer/CircleDrawer/index.tsx, packages/insight-viewer/src/Viewer/CircleViewer/index.tsx, packages/insight-viewer/src/utils/common/calculateCircleArea.spec.ts, packages/insight-viewer/src/utils/common/calculateCircleArea.ts
원에 관한 측정치를 보여주는 방식을 `radius: 000mm / radius: 000px` 에서 `Area = 000mm2 / Area = 000px2` 의 형태로 변경하였습니다.
=> VIEWER-20 / change display circle measurement

libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts, libs/insight-viewer/src/hooks/useDrawingHandler/index.ts
1. 마우스가 캔버스 밖으로 나갈 시 기존에 붙어있던 마우스 이벤트들이 전부 제거되고 다시 추가가 되지않던 문제를 확인
2. 마우스 오버 시 이벤트를 추가해주는 이벤트를 추가함
버그를 고치긴하였지만 임시 방편같은 느낌이 납니다. 선을 그리는 동안 이벤트들이 반복적으로 추가되고 제거가 되는 것을 확인 하였는데 근본적으로 해결을 위해서는 이 부분은 리팩토링이 되는 게 좋지않을까 생각합니다.
마우스가 캔버스 밖으로 나갔다가 다시 돌아오는 경우 drawing 기능이 작동하지 않음
Issue Number: https://lunit.atlassian.net/browse/VIEWER-26
마우스가 캔버스 밖으로 나갔다 오더라도 drawing 기능이 작동
=> VIEWER-26 / Fix Drawer Error

libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.styles.ts, libs/insight-viewer/src/Viewer/AnnotationViewer/AnnotationViewer.styles.ts, libs/insight-viewer/src/Viewer/CircleDrawer/CircleDrawer.styles.ts, libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx, libs/insight-viewer/src/Viewer/CircleViewer/CircleViewer.styles.ts, libs/insight-viewer/src/Viewer/CircleViewer/index.tsx, libs/insight-viewer/src/Viewer/LineViewer/index.tsx, libs/insight-viewer/src/Viewer/MeasurementDrawer/MeasurementDrawer.styles.ts, libs/insight-viewer/src/Viewer/MeasurementViewer/MeasurementViewer.styles.ts, libs/insight-viewer/src/Viewer/PolygonViewer/index.tsx, libs/insight-viewer/src/Viewer/PolylineDrawer/index.tsx, libs/insight-viewer/src/Viewer/RulerDrawer/RulerDrawer.styles.ts, libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx, libs/insight-viewer/src/Viewer/RulerViewer/index.tsx, libs/insight-viewer/src/components/EditPointer/index.tsx, libs/insight-viewer/src/types/index.ts
Annotation, Measurement 선택 영역 확장했습니다.
각각 Viewer, Drawer 에서 svg Element 를 추가한 후 storke width 를 `20px` 로 지정했습니다.
기존 Annotation, Measurement 는 정확히 Drawing 된 영역을 클릭해야 선택이 가능합니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-24
확장시킨 Annotation Viewer, Drawer 을 적용했습니다. e8a5133
확장시킨 Measurement Viewer, Drawer 을 적용했습니다. 35f54a3
=> VIEWER-24 / Annotation, Measurement Extend Select Area

libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts
`useAnnotationPointsHandler` hook 내 리랙토링 전 기준 네이밍을 현재 방식에 변경했습니다.
Points -> Annotation 으로 변경했습니다.
리팩토링 전 points 기준 네이밍을 가지고 있습니다.
(ex: `addDrawingPoints` 등)
리팩토링 후 Annotation 기준 네이밍을 가집니다.
useAnnotationPointsHandler hook 내 function 네이밍 변경 c0b3562
`addDrawingPoints` -> `addDrawingAnnotation`
=> Modify useAnnotationPointsHandler hook function naming

libs/insight-viewer/project.json, tools/scripts/publish.mjs
INSIGHT Viewer 배포 시 사용되는 publish 코드를 수정했습니다.
수정 방향성은 아래와 같습니다.
1. 기존 publish code 는 workspace 내 다양한 library (project) 를 배포하기 위한 목적입니다.
INSIGHT Viewer 에서는 다른 project 는 배포하지 않을 예정이므로 이를 INSIGHT Viewer 에 맞게 수정했습니다.
2. 현재 배포 프로세스는 `version bump 및 CHANGE_LOG 반영 후 npm 배포를 진행`할 예정입니다.
그렇기에 tag 는 root package.json 의 version 을 트래킹하면 될 것 같아 수정했습니다.
배포를 위한 version, project name, tag 설정이 필요합니다.
insight viewer 에서 publish 시 별도의 version, project name, tag 설정을 하지 않습니다.
project name 은 내부의 상수값을 선언하여 대체,
version 은 root package.json 의 version 을 사용
tag 도 마찬가지로 해당 version 을 사용합니다. f48771d
publish command 수정 [928d1a1](https://github.com/lunit-io/frontend-components/pull/307/commits/928d1a1a009b58d5768679cb1052ee38a98c028d)
=> Hotfix / publish code change

apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx, libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.types.ts, libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx, libs/insight-viewer/src/Viewer/AnnotationOverlay/index.tsx, libs/insight-viewer/src/Viewer/PolylineDrawer/PolylineDrawer.types.ts, libs/insight-viewer/src/Viewer/PolylineDrawer/index.tsx
Annotation Edit 기능 사용 시 label show 기능을 비활성화한 상태여도
label 이 표기되는 버그를 수정했습니다.
Annotation Edit 기능 사용 시, label show option 과 관계없이 항상 보였습니다.
label show 가 false 일 경우엔 label 이 표기되지 않는 것이 정상 동작입니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-58
Annotation Edit 기능 사용 시 label show option 에 따라 label 표기 여부가 결정됩니다.
label show 가 false 일 경우엔 label 이 표기되지 않습니다.
Annotation Drawer 및 PolylineDrawer 에 `showAnnotationLabel` prop 추가 
`showAnnotationLabel` 에 따라 text tag conditional render 로 문제 해결 751daa2
Annotation Drawer Docs 에서 label switch button 추가 8d82a0c
위 기능 테스트를 위해 추가했습니다.
=> VIEWER-58 / Hotfix / Annotation Drawer hide label bug fix

libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx, libs/insight-viewer/src/Viewer/CircleViewer/index.tsx, libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts, libs/insight-viewer/src/utils/common/getCircleCenterPoint.spec.ts, libs/insight-viewer/src/utils/common/getCircleCenterPoint.ts, libs/insight-viewer/src/utils/common/getCircleConnectingLine.ts, libs/insight-viewer/src/utils/common/getCircleRadius.spec.ts, libs/insight-viewer/src/utils/common/getCircleRadius.ts, libs/insight-viewer/src/utils/common/getCircleStartPoint.spec.ts, libs/insight-viewer/src/utils/common/getCircleStartPoint.ts, libs/insight-viewer/src/utils/common/getCurrentMeasurement.ts, libs/insight-viewer/src/utils/common/getDrewAnnotation.spec.ts, libs/insight-viewer/src/utils/common/getDrewAnnotation.ts, libs/insight-viewer/src/utils/common/getEditPointPosition.spec.ts, libs/insight-viewer/src/utils/common/getEditPointPosition.ts, libs/insight-viewer/src/utils/common/getMeasurement.spec.ts, libs/insight-viewer/src/utils/common/getMeasurement.ts, libs/insight-viewer/src/utils/common/getMeasurementEditingPoints.spec.ts, libs/insight-viewer/src/utils/common/getMeasurementEditingPoints.ts, libs/insight-viewer/src/utils/common/getMeasurementPointsByMode.spec.ts, libs/insight-viewer/src/utils/common/getMeasurementPointsByMode.ts, libs/insight-viewer/src/utils/common/getMovedPoints.ts
[Circle Measurement 구현 방식 변경](https://lunit.atlassian.net/browse/VIEWER-2)
- mouseDown이 circle 그리기의 시작점이 되도록 구현 방식 변경 
- 관련 좌표계 및 Measurement 생성 방식 변경
- 관련 테스트 코드 변경
- 기타 리팩토링 & circle annotation 주석 처리
- mouseDown이 circle의 중심점이 됨
- circle Measurement의 center와 관련된 마우스 좌표값은 mouseDown뿐이므로 startPoint를 기준으로 모든 관련 로직을 계산
- radius를 계산하는 함수 역시, 인자로 startPoint(mouseDown)가 오는지 혹은 centerPoint(mouseDown, mouseUp/mouseMove에 따라 계산된 값)에 따라서 나뉘어져 있지 않음
- editMode가 startPoint 혹은 endPoint일 때 이전의 start와 end 포인트를 돌려줌
- circle이 그려질 때 measurement에 전달되는 현재 좌표값은 startPoint, endPoint로 고정
- mouseDown, mouseUp/mouseMove를 받아 두 점 사이의 중점을 계산한 값이 circle의 중심점이 됨
- circle Measurement의 center와 관련된 마우스 좌표값이 mouseDown 및 계산한 center 값이 되면서 관련 로직도 2가지로 나뉘어져 처리됨
- radius를 계산하는 함수는 인자로 …
=> VIEWER-2/ Change Circle Measurement Drawing

apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx, apps/insight-viewer-docs/containers/Basic/Code.ts, apps/insight-viewer-docs/containers/Basic/DicomImageViewer.tsx, libs/insight-viewer/src/hooks/useImage/getImageIdAndScheme.spec.ts, libs/insight-viewer/src/hooks/useImage/getImageIdAndScheme.ts, libs/insight-viewer/src/hooks/useImage/index.ts, libs/insight-viewer/src/hooks/useImage/loadCornerstoneImage.ts, libs/insight-viewer/src/hooks/useImage/loadImage.spec.ts, libs/insight-viewer/src/hooks/useImage/loadImage.ts, libs/insight-viewer/src/hooks/useImage/types.ts, libs/insight-viewer/src/hooks/useMultipleImages/loadCornerstoneImages.ts, libs/insight-viewer/src/types/index.ts, libs/insight-viewer/src/utils/cornerstoneHelper/utils.ts
useImage 내부에서 사용하는 HTTP client를 외부에서 쉽게 컨트롤 가능하도록 변경하였습니다.
useImage는 변경하였지만 useImages 도 일관성있게 변경을 해주어야할 것 같습니다.
requestInterceptor 옵션을 이용하여 제한적 요청 방식 변경 가능
Issue Number: https://lunit.atlassian.net/browse/VIEWER-46
requestInterceptor는 그대로 사용가능하며 추가로 loader 옵션을 만들었으며, loader 옵션을 통해 새로운 HTTP client 지정 가능 
=> Viewer-52 / Parameterize useImage's HTTP client

libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx
Ruler Measurement 의 text move editing 기능이 정상동작하지 않는 버그를 해결했습니다.
위 버그 발생 PR: https://github.com/lunit-io/frontend-components/pull/305
관련 코드 리뷰: https://github.com/lunit-io/frontend-components/pull/305#discussion_r970504231
Ruler Measurement text move 기능 이용 시 mouse move 에 대한 변경은 화면 상에 확인할 수 없으며,
mouse up 이벤트 시, 해당 지점으로 text 가 이동하는 동작 방식입니다.
https://user-images.githubusercontent.com/88369343/192227889-832ecdc0-2dbc-45b2-a4fd-473e16800ecf.mov
Issue Number: https://lunit.atlassian.net/browse/VIEWER-63
Ruler Measurement text move 기능 이용 시 mouse move 에 대한 변경을 화면 상에 확인할 수 있습니다.
startAndEndPoint 를 기반으로 ruler text position 을 구하는 로직을 적용했습니다. 29211db
https://user-images.githubusercontent.com/88369343/192228255-214c066f-634b-4db6-93b7-501b5d84a5cd.mov
=> VIEWER-63 / modify text point logic for editing text move mode

libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx, libs/insight-viewer/src/Viewer/CircleViewer/index.tsx, libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx, libs/insight-viewer/src/Viewer/RulerViewer/index.tsx, libs/insight-viewer/src/hooks/useCircleMeasurement/index.ts, libs/insight-viewer/src/hooks/useRulerMeasurement/index.ts, libs/insight-viewer/src/hooks/useTextBox/index.ts, libs/insight-viewer/src/utils/common/modifyConnectingLine.spec.ts, libs/insight-viewer/src/utils/common/modifyConnectingLine.ts, libs/insight-viewer/src/utils/common/stringifyPoints.spec.ts, libs/insight-viewer/src/utils/common/stringifyPoints.ts
Measurement 를 그릴시TextBox와 Measurement 객체간에 연결된 선들이 TextBox 영역을 침범하던 것을 수정하였습니다
https://lunit.atlassian.net/browse/VIEWER-64
TextBox에 연결된 선이 아래의 그림과 같이 TextBox의 테두리 위의 점 4개 중 하나로 연결됩니다.
연결되는 점의 위치는 기존 TextBox의 중심으로 연결되며 TextBox의 테두리와 교차하던 점으로 부터 가장 가까운 곳으로 선택이 됩니다.
=> VIEWER-64 / Modify connecting line

libs/insight-viewer/src/Viewer/Viewer.styles.ts
Edit Pointer 의 width 값을 현재 INSIGHT View figma 기준으로 변경했습니다.
디자인팀 검수를 위해 Draft PR 로 올립니다.
edit pointer width 가 figma 기준 -1px 로 설정되어 있습니다. 
Issue Number: https://lunit.atlassian.net/browse/VIEWER-65
edit pointer width 를 figma 와 동일하게 수정했습니다.
[8727d66](https://github.com/lunit-io/frontend-components/pull/325/commits/8727d66ee7ea6ae7fc93f3529e8897b477999d31)
=> VIEWER-64 / modify edit pointer width

libs/insight-viewer/src/Viewer/AnnotationOverlay/index.tsx, libs/insight-viewer/src/Viewer/AnnotationViewer/AnnotationViewer.types.ts, libs/insight-viewer/src/Viewer/AnnotationViewer/index.tsx, libs/insight-viewer/src/Viewer/MeasurementOverlay/index.tsx, libs/insight-viewer/src/Viewer/MeasurementViewer/MeasurementViewer.types.ts, libs/insight-viewer/src/Viewer/MeasurementViewer/index.tsx, libs/insight-viewer/src/hooks/useAnnotation/index.ts, libs/insight-viewer/src/hooks/useMeasurement/index.ts, libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts, libs/insight-viewer/src/utils/common/getMeasurement.ts
Annotation, Measurement edit 모드에서 선택 시 list 에서 제거하는 방식을 변경했습니다.
list 는 유지하고 Viewer, Drawer 에서 selected Annotation drawing 여부를 결정합니다.
Annotation, Measurement edit 모드에서 선택 시 annotation list 에서 해당 요소가
삭제됩니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-43
Annotation, Measurement edit 모드에서 선택 시 annotation list 에서 해당 요소를
삭제하지 않습니다. 
Annotation Viewer 에 selectedAnnotation prop 을 추가했습니다. [889f49f](https://github.com/lunit-io/frontend-components/pull/328/commits/889f49f97b1ef60025aef2004b3ee6dfbd929c0c)
Viewer 에서는 selected Annotation 을 제외한 annotation list 를 렌더링합니다.
useAnnotation hook 에서 selected Annotation 유무에 따른 setState 값을 설정합니다. [889f49f](https://github.com/lunit-io/frontend-components/pull/328/commits/889f49f97b1ef60025aef2004b3ee6dfbd929c …
=> VIEWER-43 / Annotation, Measurement list issue

libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.types.ts, libs/insight-viewer/src/Viewer/AnnotationOverlay/AnnotationOverlay.types.ts, libs/insight-viewer/src/Viewer/AnnotationOverlay/index.tsx, libs/insight-viewer/src/Viewer/MeasurementDrawer/MeasurementDrawer.types.ts, libs/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx, libs/insight-viewer/src/Viewer/MeasurementOverlay/MeasurementOverlay.types.ts, libs/insight-viewer/src/Viewer/MeasurementOverlay/index.tsx, libs/insight-viewer/src/hooks/useMeasurementPointsHandler/types.ts
현재 활용하지 않으며 추후 활용 가능성이 낮은 device prop 및 param 을 삭제했습니다.
device prop 이 존재했습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-73
device prop 을 삭제했습니다.
device prop 을 사용하고 계신 경우, 삭제가 필요합니다.
(INSIGHT Viewer 5.x version 해당 prop 을 활용하고 있지 않았기에 삭제하셔도 동작은 동일합니다.
=> VIEWER-73 / Delete device prop and param

apps/insight-viewer-docs/containers/Interaction/Image1.tsx, libs/insight-viewer/src/hooks/useViewport.ts
useViewport 의 initial viewport parameter 가 undefined 일 경우,
reset 이 동작하지 않는 버그를 수정했습니다.
위 내용을 테스트할 수 있도록 `interaction docs` 에 initial viewport toggle switch 를 추가했습니다.
- `switch off` 상태에서 reset 을 누를 경우 `default viewport` 로 초기화됩니다.
- `switch on` 상태에서 reset 을 누를 경우,
`docs 내에 설정한 initial viewport scale 0.5` 로 초기화됩니다.
위와 같이 동작하는지 확인 부탁드립니다.
- [테스트 환경](https://insight-viewer--pr-339.f.lunit.io/interaction)
useViewport hook 의 initial viewport parameter 가 undefined 일 경우,
reset 기능이 동작하지 않습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-76
useViewport hook 의 initial viewport parameter 가 undefined 일 경우,
default viewport 로 reset 됩니다.
라이브러리 사용 앱에서 더이상 useViewport initial viewport 에 default value 를 할당하지 않아도 괜찮습니다.
=> VIEWER-76 / useViewport reset 동작 버그

libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx, libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx, libs/insight-viewer/src/components/EditPointer/index.tsx
Measurement Drawer 내 모든 polyline 혹은 circle element 에 `onMouseDown 이벤트`를 일부 삭제조치 했습니다.
DOM 레이어상 제일 상위에 있으며 영역이 제일 넓은 `extends area` 에서만 이벤트 등록을 했습니다.
drawer 관련 모든 svg element 에 onMouseDown 이벤트를 등록했습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-79
drawer 내 extends area svg element 에 onMouseDown 이벤트를 등록했습니다.
그 외 마우스 이벤트는 삭제 조치했습니다. 7e32297
=> VIEWER-79 / delete unused onMouseDown event to Drawer component

apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx, apps/insight-viewer-docs/containers/Annotation/Viewer/index.tsx, apps/insight-viewer-docs/containers/Measurement/Drawer/index.tsx, apps/insight-viewer-docs/containers/Measurement/Viewer/index.tsx, apps/insight-viewer-docs/styles/globals.css, libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx, libs/insight-viewer/src/Viewer/CircleDrawer/CircleDrawer.types.ts, libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx, libs/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx, libs/insight-viewer/src/Viewer/PolylineDrawer/PolylineDrawer.types.ts, libs/insight-viewer/src/Viewer/PolylineDrawer/index.tsx, libs/insight-viewer/src/Viewer/RulerDrawer/RulerDrawer.types.ts, libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx, libs/insight-viewer/src/Viewer/TextDrawer/TextDrawer.types.ts, libs/insight-viewer/src/Viewer/TextDrawer/index.tsx, libs/insight-viewer/src/Viewer/TextViewer/index.tsx, libs/insight-viewer/src/Viewer/Viewer.styles.ts, libs/insight-viewer/src/components/EditPointer/index.tsx, libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts, libs/insight-viewer/src/hooks/useAnnotationPointsHandler/types.ts, libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts, libs/insight-viewer/src/hooks/useMeasurementPointsHandler/types.ts, libs/insight-viewer/src/types/index.ts, libs/insight-viewer/src/utils/common/getCursorStatus.spec.ts, libs/insight-viewer/src/utils/common/getCursorStatus.ts, libs/insight-viewer/src/utils/common/setClassName.spec.ts, libs/insight-viewer/src/utils/common/setClassName.ts
https://lunit.atlassian.net/browse/IIV-194 를 해결하기 위한 작업입니다.
1. 동적인 클래스 네임을 통한 커서 스타일링 수단 추가
2. 기존에 문제가 되었던 기본 커서 스타일 제거
3. 기존에 추가되어 있던 상태용 클래스네임은 제거하였지만, 식별용 클래스네임은 유지
기존의 클래스 네임 방식은 객체에 스타일 입혀 그 객체에 스타일로 지정되어있는 커서를 보여주고 있었습니다.
하지만 이 방식은 객체가 동적인 요소인 경우, 마우스 커서를 따라다니면서 싱크가 일치해야 정상적으로 동작합니다.
하지만 가끔 마우스 커서가 빨리 움직이거나, 동적 요소의 크기가 작은 이유로 동적 요소 위를 벗어나게 되면 커서 스타일이 비활성되는 문제가 있었습니다. 그래서 현재 커서 스타일을 확인하고 캔버스 전체에 커서 스타일을 동적으로 주는 방식으로 변경하였습니다.
그리고 기존에 객체에 호버 상태를 동적으로 판별하는 데에는 내부 로직에 한계가 있고, 만약 변경하게 되더라도 성능적인 문제가 발생할 수 밖에 없는 구조였기 때문에 정적인 객체들에 스타일은 동적인 상태의 클래스가 들어 오지 않을 때 기본 값으로 주도록 변경 하였습니다.
Issue Number: https://lunit.atlassian.net/browse/IIV-194
> Please describe the …
=> Feature modify class name for cursor

libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx
Text Annotation 추가할 때 생기는 다음의 버그를 수정했습니다.
- Text Annotation 추가 시
- Annotation box 안쪽을 클릭하면 작성중인 box 가 사라짐
- 다시 클릭하면 박스 안쪽 클릭했던 위치에 Text Annotation 이 다시 나타남
- 해당 이슈가 발생하는 이유
- Drawer 에서 마우스 클릭을 하면 tempAnnotation 에 클릭한 위치와 텍스트값을 임시로 저장하여 텍스트 입력을 받음
- Text box 바깥을 클릭하면 현재까지 작성중인 text annotation 입력을 끝내고 tempAnnotation 정보를 지우도록 구현되어 있음 
- Text box 안쪽을 클릭하면 작성중인 text annotation 이 끝나지 않은 채 새로 클릭한 위치의 annotation 정보로 업데이트 -> 이 부분이 문제
Issue Number: https://lunit.atlassian.net/browse/VIEWER-80
Drawer 에서 text box 안쪽을 클릭했을 때 작성중인 text annotation 정보가 존재하면 새로운 annotation 정보로 업데이트 되지 않도록 수정
=> VIEWER-80 / fix text annotation

libs/insight-viewer/src/hooks/useDrawingHandler/index.ts
기존에는 선택된 annotation이 리스트에서 빠져 있었기 때문에 Delete 키를 누를 때 선택을 해제하면서 리스트에 다시 추가하지 않는 것으로 삭제 동작이 가능했는데, 6.0.0 부터는 리스트에서 빠지지 않기 때문에 Delete 키가 단순히 선택 해제로 동작하므로 해당 코드를 삭제합니다.
Delete 키를 누르면 annotation 선택이 해제됨
Delete 키를 눌러도 아무 동작도 하지 않음
=> feat(viewer): remove delete key handling code

libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts, libs/insight-viewer/src/utils/common/getEditPointPosition.spec.ts, libs/insight-viewer/src/utils/common/getEditPointPosition.ts, libs/insight-viewer/src/utils/common/getMeasurementEditingPoints.spec.ts, libs/insight-viewer/src/utils/common/getMeasurementEditingPoints.ts, libs/insight-viewer/src/utils/common/getMeasurementPointsByMode.spec.ts, libs/insight-viewer/src/utils/common/getMeasurementPointsByMode.ts
Circle Measurement Edit 기능 시 동작 방식을 Drawing 때와 동일하게 동작하도록 수정했습니다.
이와 더불어 Editing Pointer 도 마우스 포인터를 따라가는 방향으로 개선했습니다.
Edit 기능이 Drawing 방식과 다릅니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-55
Edit 기능과 Drawing 방식이 동일합니다.
Circle Measurement 의 Editing 동작 방식 및 Editing Pointer 위치 기능이 변경되었으니 참고 부탁드립니다.
=> VIEWER-55 / apply changed circle editting  

libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts, libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
useAnnotationPointsHandler (measurement) handler useEffect 내
isEditing 이 false 이고 selecedAnnotation(measurement) 가 null 일때
모든 states 를 초기화합니다.
이를 통해 외부에서 edit 기능 중 selectedMeasurement 를 초기화 했을 때
내부 상태값 그대로 유지되어 drawing 상태가 유지되는 버그를 해결하고자 합니다.
외부에서 `selectAnnotation(null)` 을 하더라도 editing 상태에서 drawing 상태로 변경될 뿐
selectedAnnotation 이 사라지지 않습니다.
(정확히는 selectedAnnotation 의해 생긴 useAnnotationPoinsHandler 내 annotation 이 사라지지 않음)
외부에서 `selectAnnotation(null)` 을 하면 selectedAnnotation 이 사라지고, 내부 annotation 도 삭제됩니다.
=> reset states of useAnnotationPointsHandler hook (measurement)

libs/insight-viewer/src/utils/common/getEditPointPosition.spec.ts
- [getEditPointPosition의 테스트 추가](https://lunit.atlassian.net/browse/VIEWER-84)
- 이전 [#350](https://github.com/lunit-io/frontend-components/pull/350) 작업에서 누락되었던 circle의 edit points 관련 테스트를 추가합니다.
=> VIEWER-84 / add tests of circle edit points

.github/workflows/insight-viewer-production.yml
현재 프로덕션 배포인 `insight-viewer.lunit.io`에 새 사이트를 배포할 경우 Cloudfront에서 캐시한 index.html 파일을 전달하여 새 사이트를 조회할 수 없는 문제가 있습니다. `Cache-control: no-store, no-cache, must-revalidate` 헤더를 추가하여 CDN과 브라우저에서 index.html을 캐시하는 것을 방지합니다.
참고: https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Cache-Control
프로덕션 배포를 수정해야 하므로 master로 머지하겠습니다.
Cloudfront 캐시가 index.html에 적용되어 새 배포시에도 이전 사이트가 조회됨
index.html은 캐시 설정에서 제외되어 요청마다 최신 사이트가 조회됨
=> chore(docs): add metadata to set cache header

apps/insight-viewer-docs-e2e/src/e2e/annotation.drawer.cy.ts, apps/insight-viewer-docs-e2e/src/support/utils.ts, apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx, libs/fixtures/src/annotation/polygons.ts, libs/insight-viewer/src/hooks/useAnnotation/index.ts
* useAnnotation에 reset 기능을 추가합니다. c6c66e1c6da58842d0c62f2a93e734f65aba5d9d
* cypress에 lint error가 발생하여 수정하였습니다 [관련문서 link](https://docs.cypress.io/guides/references/best-practices#Assigning-Return-Values) a2137b110981da5413dde9708186c197b9d3ed13
* POLYGON_ANNOTATION mock의 index 0번을 initial polygon annotation mock을 옮겼습니다.
test나 docs에 initial 값으로 보여집니다. c10c5adcc796882df6cd1a383250e393f5a7a4bc
* 관련 testing 추가 d13213395c635a3a458d6f1d76668b485f2b1745
initialAnnotation 값이 있는 상태에서 resetAnnotation을 호출하면 initialAnnotation 만 남습니다. 
initialAnnotation 값이 없는 상태에서 resetAnnotation을 호출하면 annotation data가 []이 됩니다.
Annotation Drawer docs에 reset button이 추가되었습니다.
> If this PR contains a breaking change, please describe the impact and migration …
=> VIEWER-69 / add reset annotation

libs/insight-viewer/src/hooks/useImageDisplay/index.ts
`useImageDisplay` hook 에서 cornerstone displayImage 로 이미지 디스플레이 직후에
`cornerstone resize` method 를 실행하도록 로직을 추가했습니다.
`cornerstone resize` 는 아래와 같은 시나리오에서만 동작합니다.
1. 제일 처음 viewer 렌더링 시점
2. image wrapper 사이즈 변경
`cornerstone resize` 는 아래와 같은 시나리오에서만 동작합니다.
1. 제일 처음 viewer 렌더링 시점
2. image wrapper 사이즈 변경
3. viewer 에 image 가 display 되는 시점 (추가)
=> hotfix / apply Cornerstone resize to useImageDisplay

apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx, apps/insight-viewer-docs/containers/Measurement/Drawer/index.tsx
Annotation, Measurement Drawing 페이지에 단축키를 추가합니다.
isDrawing, isEditing은 스위치를 마우스로 클릭해서만 변경할 수 있음
Issue Number: VIEWER-90
단축키 D, E로 각 Props를 변경 가능
=> VIEWER-90 / feat(docs): add shortkeys in drawing page

apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx
annotation drawer 페이지에서 
initial annotation 값을 annotation mode에 따라 다르게 설정한 탓에
mode가 바뀔때마다 mode와 관련된 annotation만 보이는 현상이 있었습니다. 
annotation viewer 페이지를 보시면 어떤 현상인지 참고가 되실 것 같습니다.   
이전처럼 모든 mode가 보이도록 수정하였습니다. 
=> chore(docs): fix initialAnnotation on annotation page

libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.types.ts, libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx, libs/insight-viewer/src/Viewer/AnnotationOverlay/index.tsx, libs/insight-viewer/src/Viewer/MeasurementDrawer/MeasurementDrawer.types.ts, libs/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx, libs/insight-viewer/src/Viewer/MeasurementOverlay/index.tsx, libs/insight-viewer/src/components/EditPointer/index.tsx, libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts, libs/insight-viewer/src/hooks/useAnnotationPointsHandler/types.ts, libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts, libs/insight-viewer/src/hooks/useMeasurementPointsHandler/types.ts
Annotation, Measurement를 선택한 상태에서 isDrawing을 false로 변경하면 선택한 객체가 뷰어에서 숨겨지는 현상을 수정합니다.
isDrawing을 false로 변경하면 선택한 객체가 뷰어에서 숨겨지며, true로 변경하면 다시 나타납니다.
Issue Number: [VIEWER-91]
isDrawing을 false로 변경하면 isEditing을 false로 변경했을때와 동일하게 선택이 해제되며, 숨겨지지 않습니다.
또한 Hover, Click 동작이 비활성화됩니다.
[VIEWER-91]: https://lunit.atlassian.net/browse/VIEWER-91?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VIEWER-91 / Fix/select disappear

libs/insight-viewer/src/hooks/useDrawingHandler/index.ts
마우스 왼쪽 클릭에 한해서 Annotation, Measurement Drawing 기능을 활성화 할 수 있도록 수정했습니다.
모든 마우스 down 이벤트에서 Annotation, Measurement Drawing 이 가능합니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-121
마우스 왼쪽 클릭에 한해서 Mouse down 로직이 돌아가도록 조건문 추가했습니다. [cc0827d](https://github.com/lunit-io/frontend-components/pull/373/commits/cc0827da55c1c76aba5b7df23c699a8c251a6413)
이를 통해 마우스 왼쪽 클릭에 한해서 Drawing 기능이 활성화 됩니다.
`event.witch` 의 경우 `deprecated` 처리된 상태이지만 라이브러리이므로 모든 브라우저 대응이 필요할 듯하여
조건문에 포함했습니다.
참고 문서: https://www.w3schools.com/jsref/event_button.asp
https://www.quirksmode.org/js/events_properties.html#button
내부 동작 방식이 변경되었습니다.
만약 전체 마우스를 통해 Drawing 을 하고 계셨던 경우, 라이브러리 사용자께선 이에 대한 조치가 필요합니다.
=> VIEWER-121 / add mouse left click validation when annotation drawing

apps/insight-viewer-docs-e2e/src/e2e/annotation.drawer.cy.ts, apps/insight-viewer-docs-e2e/src/e2e/annotation.viewer.cy.ts, apps/insight-viewer-docs-e2e/src/e2e/measurement.viewer.cy.ts, apps/insight-viewer-docs-e2e/src/support/utils.ts, apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx, apps/insight-viewer-docs/containers/Annotation/Viewer/index.tsx, apps/insight-viewer-docs/containers/Measurement/Viewer/index.tsx
Annotation, Measurement Viewer 스펙이 변경됨에 따라 불필요한 E2E 테스트 코드를 삭제조치 했습니다.
기타 테스트 실패하는 케이스에 대한 수정도 진행했습니다.
E2E 테스트 github action 은 별도의 PR 에서 진행할 예정입니다. 
더불어 Cypress 테스팅 병렬화 작업 역시 별도의 PR 에서 진행할 예정입니다.
해당 PR 에선 E2E 테스트 통과를 목적으로 하고 있습니다.
**로컬 환경에서 E2E 테스트 실행 및 테스트 통과 여부 확인 부탁드립니다.**
일부 테스트 코드가 동작하지 않습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-8
Initial Annotation 유무를 결정할 수 있게 Switch 를 추가했습니다. f517164
(이는 Initial Annotation 유무에 따른 화면 변화를 체크하기 위한 목적이며 이에 대한 E2E 테스트 대응을 위한 작업입니다.)
initial Annotation 유무를 결정하는 switch 를 기본 true 에서 false 로 전환하기 위해
cypress handling 코드를 추가했습니다. bd83799
Annotation, Measurement Viewer delete 관련 docs 로직 및 test 코드를 삭제했습니다. 8c8f4a8
이는 [Annotation select 시, isDrawing 을 false 로 변경할 경우 발생하는 이슈 해결 …
=> VIEWER-8 / fix Annotation, Measurement test code

apps/insight-viewer-docs/containers/Interaction/Tabs.tsx, libs/insight-viewer/src/hooks/useViewport.ts, libs/insight-viewer/src/hooks/useViewportUpdate.ts
Legacy useViewport reset 기능이 한 번 사용한 후 다시 reset 기능 사용 시,
동작하지 않는 버그를 해결합니다.
useViewport 의 reset 기능을 한 번 사용한 후 다시 사용할 경우, reset 을 하지 않습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-124
reset 버튼을 클릭할 경우 항상 viewport 를 초기 상태로 reset 합니다.
useViewport hook 의 resetViewport function 에서 setState 의 
prevState 를 활용하는 방향으로 수정했습니다.     316a9d9
useViewportUpdate hook 에서 reset 할 경우 isLegacyViewport 값을 true 로 설정합니다.     783174e
useViewportUpdate hook 의 reset 은 레거시 코드일 경우에만 동작합니다.
해당 값 할당을 하지 않는 이슈로 인해 한 번 사용 후, isLegacyViewport 값이 undefined 로 처리되어
이 후 reset 시 상위 조건문에서 걸러지면서 버그가 발생했습니다.
=> VIEWER-124 / fix useViewport reset bug

apps/insight-viewer-docs/containers/Interaction/Image2.tsx, libs/insight-viewer/src/Viewport/useViewport/index.ts, libs/insight-viewer/src/Viewport/useViewport/type.ts
이전 [useViewport Renewal PR](https://github.com/lunit-io/frontend-components/pull/371) 을 통해 추가된 hook 의 사용성을 개선했습니다.
useViewport image, element parameter 를 Ref 로 관리하여 이 두 데이터를 사용하는 쪽에서
`image`, `element` 에 대한 디펜던시를 제거하는 방향으로 변경했습니다.
(이와 동시에 한 번만 선언하는 function 은 useViewport hook 외부에 선언했습니다.)
이전 구조는 `image`, `element`, `fitScale` option 과 `return function` 간 커플링이 존재하며,
이에 대한 싱크를 사용하는 쪽에서 신경써야했습니다.
(parameter 에 있는 fitScale 을 그대로 사용하는 것도 해당 이슈에 영향을 줍니다.)
현재 구조는 viewport 와 관련된 내용은 setState 의 prevState 를 활용하여 이전보다 안정감 있게 값을 서빙하여
parameter 와 관계없이 안정된 값을 전달한다는 보장이 됩니다.
이렇게 개선하는 이유는 아래와 같습니다.
현재 useViewport hook 내 함수는 return value 에 포함되어 있습니다.
이 과정에서 이전 구조는 라이브러리 사용자 입장에선 최신의 값이 반영된 setViewport function 여부를 보장하기 어렵습니다. 
(fitScale, image, element 등에 대한 디펜던시가 전부 걸려있으므로.)
이 구조는 라이브러리 사용자 입장에서 까다로운 이슈로 …
=> VIEWER-125 / apply useRef to useViewport image, element parameter

apps/insight-viewer-dev/containers/Annotation/Drawer/index.tsx, apps/insight-viewer-dev/containers/Measurement/Drawer/index.tsx, libs/insight-viewer/src/Annotation/components/AnnotationDrawer/AnnotationDrawer.types.ts, libs/insight-viewer/src/Annotation/components/AnnotationDrawer/index.tsx, libs/insight-viewer/src/Annotation/components/AnnotationOverlay/AnnotationOverlay.types.ts, libs/insight-viewer/src/Annotation/components/AnnotationOverlay/index.tsx, libs/insight-viewer/src/Annotation/components/AnnotationsViewer/AnnotationViewer.types.ts, libs/insight-viewer/src/Annotation/hooks/useCreatingAnnotation/index.ts, libs/insight-viewer/src/Annotation/types.ts, libs/insight-viewer/src/hooks/useDrawingHandler/index.ts, libs/insight-viewer/src/hooks/useDrawingHandler/types.ts
AnnotationOverlay onChange 적용 전, 기존 props type 및 네이밍 개선 작업을 진행합니다.
_(onChange 와 함께 올리기엔 수정 사항이 많아 PR 을 분리합니다.)_
select, hover 관련 props 는 항상 필수값으로 들어갑니다. 
isEditing props 를 통해 Annotation Remove, Select 기능을 지원합니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-136
select, hover 관련 props 는 옵셔널입니다. 916f5a8
(사용하지 않을 경우 해당 props 를 넣지 않아도 됩니다.)
ClickAction 타입을 추가합니다. 15d5bad
AnnotationOverlay 에서 Click 시 실행할 액션을 지정합니다.
isEditing 의 대체 prop 이며, 보다 명확한 네이밍을 제공하기 위해 type 과 네이밍을 수정했습니다.
isEditing prop 에서 clickAction 으로 수정합니다. 7ca182e
isEditing 대신 clickAction 을 사용해야합니다.
이와 더불어 boolean 에서 'remove' 혹은 'select' 와 같은 string 타입으로 수정해야합니다.
=> VIEWER-136 / AnnotationOverlay Props type, 네이밍 개선

apps/insight-viewer-dev/containers/Annotation/Drawer/index.tsx, libs/insight-viewer/src/Annotation/types.ts, libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.types.ts, libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx, libs/insight-viewer/src/Viewer/AnnotationOverlay/AnnotationOverlay.types.ts, libs/insight-viewer/src/Viewer/AnnotationOverlay/index.tsx, libs/insight-viewer/src/Viewer/PolylineDrawer/PolylineDrawer.types.ts, libs/insight-viewer/src/Viewer/PolylineDrawer/index.tsx, libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts, libs/insight-viewer/src/hooks/useAnnotationPointsHandler/types.ts, libs/insight-viewer/src/hooks/useAnnotationPointsHandler/utils/getInitialAnnotation.ts, libs/insight-viewer/src/index.ts, libs/insight-viewer/src/types/index.ts
사용하지 않는 LineHead prop 및 관련 타입, 로직을 삭제합니다.
lineHead prop 을 통해 Line Annotation, Arrow Annotation 선택을 할 수 있습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-140
Annotation type 및 mode prop 을 통해 Line, Arrow 를 구분합니다.
lineHead 는 더이상 사용할 수 없습니다.
`lineHead` 를 사용하는 대신 mode prop 의 `arrowLine` 을 사용해야합니다.
=> VIEWER-140 / delete lineHead prop and type

apps/insight-viewer-dev/containers/Annotation/Drawer/index.tsx, apps/insight-viewer-dev/containers/Interaction/Code.ts, apps/insight-viewer-dev/containers/Interaction/Custom.tsx, apps/insight-viewer-dev/containers/Interaction/Image1.tsx, apps/insight-viewer-dev/containers/Overlay/Code.ts, apps/insight-viewer-dev/containers/Overlay/index.tsx, apps/insight-viewer-dev/containers/UseOverlayContext/Contour/index.tsx, apps/insight-viewer-dev/containers/UseOverlayContext/Heatmap/index.tsx, apps/insight-viewer-dev/containers/Viewport/Code.ts, apps/insight-viewer-dev/containers/Viewport/Image1.tsx, apps/insight-viewer-dev/containers/Viewport/Image2.tsx, apps/insight-viewer-dev/containers/ViewportReset/MultiFrame/Code.ts, apps/insight-viewer-dev/containers/ViewportReset/MultiFrame/Images.tsx, apps/insight-viewer-dev/containers/ViewportReset/SingleFrame/Code.ts, apps/insight-viewer-dev/containers/ViewportReset/SingleFrame/Image1.tsx, apps/insight-viewer-dev/containers/ViewportReset/SingleFrame/Image2.tsx, libs/insight-viewer/src/const/index.ts, libs/viewport/src/useViewport/index.ts, libs/viewport/src/useViewport/type.ts
useViewport hook 의 element 받는 방식을 `ref.current` 가 아닌 ref 그 자체를 받는 방향으로 수정합니다.
이는 InsightViewer Component 의 prop 와 통일된 방식을 제공하기 위함입니다.
또한 기존 `HTMLDivElement | undefined` 타입에서 `HTMLDivElement | null` 타입으로 변경합니다.
이 역시도 InsightViewer Component prop 의 타입과 동일하게 제공하기 위함입니다.
_(이 부분 때문에 타입 에러가 발생하는 것을 수정합니다.)_
useViewport hook 에서 `HTMLDivElement | undefined` 타입을 받습니다.
ref.current 을 인자로 받습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-156
useViewport hook 에서 `HTMLDivElement | null` 타입을 받습니다.
ref 자체를 인자로 받습니다.
useViewport hook 의 parameter 가 변경되어 수정이 필요합니다.
=> VIEWER-156 / useViewport hook parameter type

.github/workflows/insight-viewer-feature.yml, libs/insight-viewer/src/hooks/useInteraction/useHandleDrag/index.ts
drag interaction 의 이벤트 실행 범위를 `document(브라우저 전체 영역)` 에서
`insight viewer element(viewer 영역)` 으로 제한합니다.
위 조치는 Annotation Drawing 과 동일한 영역을 제공하여 사용자에게 혼동을 줄이기 위함입니다.
_(또한 예상치 못한 동작을 방지하기 위한 목적도 있습니다.)_
이 과정에서 viewer element 영역을 벗어날 경우, mouse move 에 대한 observable 이 끊기도록
mouse leave observable 추가 및 `takeUntil` 에 mouse leave 를 추가하여
mouse up, mouse event 일 때 mouse move observable 이 끊기도록 수정했습니다. 
위 조치를 하지 않을 경우 아래와 같은 버그가 발생합니다. 
1. viewer 영역 내에서 mouse move 를 통해 drag interaction 실행(영상 이미지 움직임)
2. viewer 영역을 벗어난 후 mouse up (영상 이미지 움직이지 않음)
3. viewer 영역으로 복귀하여 mouse move (영상 이미지 다시 움직임)
drag (mouse down -> mouse move) 를 하지 않았음에도
영상 이미지가 움직이게 되어 의도에 맞지 않게 동작합니다.
- [drag 영역이 document 로 잡혀있는 환경 링크](https://insight-viewer.s.lunit.io/interaction)
drag …
=> VIEWER-159 / drag event 실행 영역 제한 및 개선

libs/annotation/src/hooks/useMouseEvent/index.ts, libs/insight-viewer/src/hooks/useInteraction/useHandleDrag/index.ts
Drag Interaction 과 Annotation Drawing 를 함께 사용할 시,
Image 가 움직이고, Annotation Drawing 이 함께 동작하는 버그를 수정합니다.
버그 수정 후 동작 방식은 다음과 같습니다.
Drag Interaction, Annotation Drawing 이 함께 실행될 경우,
Drag Interaction 이 우선 시 되며, Annotation Drawing 은 사용할 수 없습니다.
Drag Interaction 이 없을 경우, Annotation Drawing 은 사용 가능합니다.
Drag Interaction, Annotation Drawing 이 동시에 발생합니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-158
Drag Interaction, Annotation Drawing 이 모두 활성화 되어 있을 경우,
Drag Interaction 만 발생합니다.
이에 대한 조치는 Drag Interaction 발생 시, `stopPropagation` 을 사용하여
이벤트가 캡처링/버블링 단계에서 전파되지 않도록 하여 하위에 있는 이벤트를 발생시키지 않도록
수정합니다.
- [stopPropagation MDN](https://developer.mozilla.org/ko/docs/Web/API/Event/stopPropagation)
> If this PR contains a breaking change, please describe …
=> VIEWER-158 / Annotation, Interaction 동시 사용 불가 버그 수정

apps/insight-viewer-dev/components/OverlayLayer/index.tsx, apps/insight-viewer-dev/containers/Interaction/Canvas.tsx, apps/insight-viewer-dev/containers/Overlay/Code.ts, apps/insight-viewer-dev/containers/UseOverlayContext/Contour/index.tsx, apps/insight-viewer-dev/containers/UseOverlayContext/Heatmap/index.tsx, apps/insight-viewer-dev/containers/Viewport/Code.ts, apps/insight-viewer-dev/containers/Viewport/Image1.tsx, apps/insight-viewer-dev/containers/Viewport/Image2.tsx, apps/insight-viewer-dev/containers/ViewportReset/MultiFrame/Code.ts, apps/insight-viewer-dev/containers/ViewportReset/MultiFrame/Images.tsx, apps/insight-viewer-dev/containers/ViewportReset/SingleFrame/Code.ts, apps/insight-viewer-dev/containers/ViewportReset/SingleFrame/Image1.tsx, apps/insight-viewer-dev/containers/ViewportReset/SingleFrame/Image2.tsx, libs/viewport/src/index.ts
@lunit/insight-viewer/viewport 에서 Viewport 관련 타입을 import 할 수 있도록 수정합니다.
Viewport 관련 type 을 import 할 때 아래와 같이 사용합니다.
```ts
import type { Viewport } from "@lunit/insight-viewer";
```
Issue Number: https://lunit.atlassian.net/browse/VIEWER-160
Viewport 관련 type 을 import 할 때 아래와 같이 사용할 수 있습니다.
```ts
import type { Viewport } from "@lunit/insight-viewer/viewport";
```
=> VIEWER 160 / viewport subpath 에서 Viewport 관련 type export

libs/insight-viewer/README.md, libs/insight-viewer/package.json, package.json
insight-viewer 라이브러리의 package.json 과 README 를 업데이트합니다.
이를 통해 NPM 에 개시될 때 의도에 맞는 README 과 등록될 예정이며,
`keyword`, `repo`, `homepage` 정보가 표기됩니다.
- [package.json docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json)
Root 의 README 가 아닌 viewer 의 README 가 패키지가 포함됩니다.
이로 인해 의도와 다른 README 가 NPM 에 등록됩니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-54
viewer 의 업데이트된 README 가 NPM 에 등록됩니다.
이와 더불어 repo, homepage, keyword 정보가 NPM 에 표기됩니다.
=> VIEWER-54 / package.json 업데이트 및 viewer README 업데이트

libs/annotation/src/components/AnnotationOverlay/utils/addAnnotation.ts
Annotation 추가 시, `onAdd` 의 결과값이 `onChange` 에 반영되지 않는 이슈를 해결합니다.
onAdd 의 값이 반영된 `addedTargetAnnotation` 를 사용하는 것이 아닌
처음 넘겨받은 pure Annotation 객체를 onChange 에 전달하고 있습니다.
위 방식으로 인해 onAdd 로 커스텀한 객체가 onChange 실행 시 전달되는 Annotations 배열에
반영되지 않습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-162
onAdd 의 값이 반영된 `addedTargetAnnotation` 을 onChange 에 전달합니다.
이를 통해 onAdd 로 커스텀한 객체가 onChange 실행 시 전달되는 Annotations 배열에 반영됩니다.
유저는 onAdd props 를 통해 Annotation 객체에 필드를 유연하게 수정할 수 있습니다.
=> VIEWER-162 / Annotation 추가 시 onAdd 의 값이 반영되지 않는 버그 해결

libs/annotation/src/components/AnnotationViewer/index.tsx, libs/annotation/src/types.ts
data attribute 가 적용되지 않는 이슈를 해결합니다.
AnnotationOverlay 의 onAdd prop 을 활용, annotation 의 `dataAttrs` 값을 할당하면 data attribute 가 적용됩니다.
이와 함께 dataAttrs 의 타입을 [Template Literal Types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) 를 적용하여 보다 정확한 값을 기입할 수 있도록 개선했습니다.
```tsx
<AnnotationOverlay
{...props}
onAdd={(annotation) => {
const addedAnnotation = { ...annotation }
addedAnnotation.dataAttrs = { 'data-index': '1' }
return addedAnnotation
}}
/>
```
data attribute 를 적용할 수 없습니다.
Issue Number: https://lunit.atlassian.net/browse/VIEWER-163
annotation 추가 시 data attribute 를 지정할 수 있습니다.
=> VIEWER-163 / data Attribute 적용

apps/insight-viewer/src/app/ControlledViewer.tsx, apps/insight-viewer/src/app/MultiViewer.tsx, apps/insight-viewer/src/app/app.tsx, apps/insight-viewer/src/app/image.ts, libs/core/src/Subscribable.ts, libs/core/src/eventHandler/EventHandler.ts, libs/core/src/renderViewport/RenderingStackViewport.ts, libs/core/src/viewerFactory/ViewerFactory.ts, libs/react-dicom-viewer/src/DicomViewer.tsx, libs/react-dicom-viewer/src/useStackViewport.ts
`DicomViewer` 를 React Controlled Component 로 사용할 수 있도록 기능을 구현합니다.
1. pan, zoom 과 같이 DICOM 에 변경이 있을 경우, `onChange` 를 호출하여 상태를 업데이트 합니다.
2. `DicomViewer` 의 viewerInfo prop 의 값이 변경될 경우, 이를 이미지에 반영하여 리렌더링 합니다.
- `useStackViewport` 에서 useEffect 를 통해 eventCallback 함수로 onChange 를 할당했습니다.
- `useStackViewport` 에서 useEffect 를 통해 viewerInfo prop 이 변경될 경우, viewerFactory 의 `updateSnapshot` 을 호출합니다.
- `viewerFactory` 의 `updateSnapshot` 을 통해 viewport 를 업데이트 합니다.
N/A
`DicomViewer` 가 Controlled Component 형태로 동작합니다.
https://github.com/user-attachments/assets/a0a5a327-4782-4bd2-adc8-0cc7acf0a466
=> insight-viewer v8 Controlled Component

libs/react-dicom-viewer/src/DicomViewer.tsx
v7 의 `InsightViewer`, v8 의 `DicomViewer` 모두, 
사용 시 상위 element 에서 viewer 의 width, height 를 지정하는 과정을 거쳐야합니다.
이는 사용성 저하의 원인 중 하나로 v8 의 `DicomViewer` 는 기본적인 width, height 를 지정하여
사용자가 style wrapper element 를 선언하지 않고, `DicomViewer` 를 독립적으로 사용할 수 있도록
개선합니다.
사용자는 `DicomViewer` 를 사용하기 위해 상위 Wrapper 선언 및 스타일 지정이 필요합니다.
사용자는 상위 Wrapper 선언 없이 `DicomViewer` 을 독립적으로 사용할 수 있습니다.
=> [VIEWER-169] DicomViewer default style 적용
